---
title: "C4 Model"
output: html_notebook
---

```{r, include=FALSE}
InputFromFile = readline(prompt = "Read Data From CSV File? ~ Y/N   = ")
if (InputFromFile == "Y"){
  wd = readline(prompt = "File Folder Path =")
  setwd = (wd)
  filename = readline(prompt = "File Name (Including File Type) = ")
  input <- read.csv(file = filename,sep = ",",header = T,stringsAsFactors = T)
}else{
  library("shiny")
  runApp()
  
}
```

```{r, include=FALSE}
#Create Dictionary of Values

Cell_IDs = levels(input$Cell.ID)
inputvalues = {}
for (CellID in Cell_IDs) {
  inputvalues[CellID] = input$Value[input$Cell.ID ==CellID]
}

#Input Values As As Table
inputtab <- matrix(data = inputvalues)
rownames(inputtab) <- c(names(inputvalues))
colnames(inputtab) <- c("Value")
inputtab
```

```{r, include=FALSE}
#Convert Dict To Variables
B4 = inputvalues["B4"]
B5 = inputvalues["B5"]
B6 = inputvalues["B6"]
B7 = inputvalues["B7"]
B8 = inputvalues["B8"]
B9 = inputvalues["B9"]
B10 = inputvalues["B10"]
B11 = inputvalues["B11"]
B12 = inputvalues["B12"]
B13 = inputvalues["B13"]
B14 = inputvalues["B14"]
B15 = inputvalues["B15"]
B16 = inputvalues["B16"]
B17 = inputvalues["B17"]
B18 = inputvalues["B18"]
B19 = inputvalues["B19"]
B20 = inputvalues["B20"]
B21 = inputvalues["B21"]
B22 = inputvalues["B22"]
B23 = inputvalues["B23"]
B24 = inputvalues["B24"]
B25 = inputvalues["B25"]
B26 = inputvalues["B26"]
B27 = inputvalues["B27"]
B28 = inputvalues["B28"]
B29 = inputvalues["B29"]
B30 = inputvalues["B30"]
B31 = inputvalues["B31"]
B32 = inputvalues["B32"]
```

```{r, include=FALSE}
#Outputs

#Light Reactions
Mlightrxns <- {}
BSlightrxns <- {}

#Mesophyll Light Reactions
Mlightrxns["Iinc"] = G6 = B4/(1+B10)
Mlightrxns["Y(J)LL"] = G7 = B11*B12
Mlightrxns["f(PPFD)"] = G8 = 1-max(0,(B25*G6+1-B26)/(2*B27)-sqrt((B25*G6+1-B26)^2-4*B25*G6*B27*(1-B26))/(2*B27)+B26)
Mlightrxns["f(CM)"] = G9 = max(0,(B22*B5+1-B23)/(2*B24)-sqrt((B22*B5+1-B23)^2-4*B22*B5*B24*(1-B23))/(2*B24)+B23)
Mlightrxns["Y(2)"] = G10 = G8*B11*G9
Mlightrxns["I2 0"] = G11 = G6*B12
Mlightrxns["J2 0"] = G12 = G11*B11
Mlightrxns["I1 0"] = G13 = G12/B17
Mlightrxns["x"] = G14 = B20/(1-B20+B11)
Mlightrxns["I2"] = G15 = (1/B11-G14)*G12
Mlightrxns["I1"] = G16 = (1+G14)*G13
Mlightrxns["Itot"] = G17 = G15+G16
Mlightrxns["J2"] = G18 = G15*G10
Mlightrxns["J1"] = G19 = G18/(1-B20)
Mlightrxns["JATP"] = G20 = G18/B16+2*B15*G18/(B16*(1-B20))+2*B18*B20*G18/(B16*(1-B20))+(1-B15)*G18/(B16*(1-B20))
G22 = 0.0000004*B6+B13
Mlightrxns["JNADPH"] = G21 = (1-B20-G22)*G18/(2*(1-B20))
Mlightrxns["fpseudo wwc"] = G22


Mlightrxnstab <- matrix(data = Mlightrxns)
rownames(Mlightrxnstab) <- c(names(Mlightrxns))
colnames(Mlightrxnstab) <- c("Value")
print("M Light Reactions")
Mlightrxnstab


#Bundle Sheath Light Reactions

BSlightrxns["Iinc"] = H6 = G6*B10
BSlightrxns["Y(J)LL"] = H7 = B11*B12
BSlightrxns["f(PPFD)"] = H8 = 1-max(0,(B25*H6+1-B26)/(2*B27)-sqrt((B25*H6+1-B26)^2-4*B25*H6*B27*(1-B26))/(2*B27)+B26)
BSlightrxns["f(CM)"] = H9 = 
max(0,(B22*B5+1-B23)/(2*B24)-sqrt((B22*B5+1-B23)^2-4*B22*B5*B24*(1-B23))/(2*B24)+B23)
BSlightrxns["Y(2)"] = H10 = H8*B11*H9
BSlightrxns["I2 0"] = H11 = H6*B12
BSlightrxns["J2 0"] = H12 = H11*B11
BSlightrxns["I1 0"] = H13 = H12/B17
BSlightrxns["x"] = H14 = B21/(1-B21+B11)
BSlightrxns["I2"] = H15 = (1/B11-H14)*H12
BSlightrxns["I1"] = H16 = (1+H14)*H13
BSlightrxns["Itot"] = H17 = H15+H16
BSlightrxns["J2"] = H18 = H15*H10
BSlightrxns["J1"] = H19 = H18/(1-B21)
BSlightrxns["JATP"] = H20 = H18/B16+2*B15*H18/(B16*(1-B21))+2*B19*B21*H18/(B16*(1-B21))+(1-B15)*H18/(B16*(1-B21))
H22 = 0.0000004*B6+B14
BSlightrxns["JNADPH"] = H21 = (1-B21-H22)*H18/(2*(1-B21))
BSlightrxns["fpseudo wwc"] = H22


BSlightrxnstab <- matrix(data = BSlightrxns)
rownames(BSlightrxnstab) <- c(names(BSlightrxns))
colnames(BSlightrxnstab) <- c("Value")
print("BS Light Reactions")
BSlightrxnstab

```

```{r, include=FALSE}
#CBS Pre-Calculations
K16 = G21+H21
P9 = B9*B30
O15 = B5
P16 = B6+1/4*H18/(0.047*B7)

```



```{r, include=FALSE}
V20.1 = 5184*B29*H20^2-21204*K16^2*B29-52*B9^2*B29-5184*G20^2*B29-20736*B29*P9^2+5184*G20^2+34596*K16^2+676*B9^2+5184*H20^2+1296*G20^2*B29^2-3447*K16^2*B29^2+2052*K16^2*B29^3+324*K16^2*B29^4-311*B9^2*B29^2+12*B9^2*B29^3+36*B9^2*B29^4+20736*P9^2+20736*B7^2*O15^2-3888*B29^2*H20^2-2592*B29^3*H20^2+1296*B29^4*H20^2+5184*B29^2*H21^2-5184*B29^3*H21^2+1296*B29^4*H21^2+5184*B29^2*P9^2-26784*G20*K16-3744*G20*B9+9672*K16*B9+10368*G20*H20-26784*K16*H20-3744*B9*H20+20736*G20*P9-53568*K16*P9-7488*B9*P9+20736*H20*P9+2592*G20^2*B29^2*B32+13194*K16^2*B29^2*B32-648*K16^2*B29^4*B32+314*B9^2*B29^2*B32-72*B9^2*B29^4*B32+21600*K16^2*B29^2*B28-1512*K16^2*B29^3*B28-1296*K16^2*B29^4*B28+672*B9^2*B29^2*B28+264*B9^2*B29^3*B28-144*B9^2*B29^4*B28+2592*B29^2*H20^2*B32+5184*B29^3*H20^2*B32-2592*B29^4*H20^2*B32-5184*B29^3*H21^2*B32+2592*B29^4*H21^2*B32+15552*B29^3*H20^2*B28-5184*B29^4*H20^2*B28-20736*B29^2*H21^2*B28+20736*B29^3*H21^2*B28-5184*B29^4*H21^2*B28+21600*G20*K16*B29+2016*G20*B9*B29+20736*B7*G20*O15-3336*K16*B9*B29-53568*B7*K16*O15-7488*B7*B9*O15-10368*G20*B29*H21-5184*K16*B29*H20-1728*B9*B29*H20+26784*K16*B29*H21+20736*B7*H20*O15-20736*G20*B29*P9+3744*B9*B29*H21+43200*K16*B29*P9+4032*B9*B29*P9+41472*B7*P9*O15-10368*B29*H20*H21-20736*B29*H21*P9+36*B31^2*K16^2*B29^2-36*B31^2*K16^2*B29^3+9*B31^2*K16^2*B29^4+100*B31^2*B9^2*B29^2-100*B31^2*B9^2*B29^3+25*B31^2*B9^2*B29^4+5184*B7^2*B29^2*O15^2+1296*G20^2*B29^2*B32^2+3249*K16^2*B29^2*B32^2-2052*K16^2*B29^3*B32^2+324*K16^2*B29^4*B32^2+B9^2*B29^2*B32^2-12*B9^2*B29^3*B32^2+36*B9^2*B29^4*B32^2+82944*B7^2*P16^2*B8^2+5184*K16^2*B29^2*B28^2-5184*K16^2*B29^3*B28^2+1296*K16^2*B29^4*B28^2+576*B9^2*B29^2*B28^2-576*B9^2*B29^3*B28^2+144*B9^2*B29^4*B28^2+1296*B29^2*H20^2*B32^2-2592*B29^3*H20^2*B32^2+1296*B29^4*H20^2*B32^2+1296*B29^4*H21^2*B32^2+20736*B29^2*H20^2*B28^2-20736*B29^3*H20^2*B28^2+5184*B29^4*H20^2*B28^2+20736*B29^2*H21^2*B28^2-20736*B29^3*H21^2*B28^2+5184*B29^4*H21^2*B28^2-1512*G20*K16*B29^2-1296*G20*K16*B29^3+792*G20*B9*B29^2-432*G20*B9*B29^3+2232*B31*K16^2*B29-520*B31*B9^2*B29-3054*K16*B9*B29^2+720*K16*B9*B29^3+216*K16*B9*B29^4-7776*G20*B29^2*H20+2592*G20*B29^3*H20+10368*G20*B29^2*H21-2592*G20*B29^3*H21+20088*K16*B29^2*H20-2808*K16*B29^3*H20-1296*K16*B29^4*H20+2808*B9*B29^2*H20+360*B9*B29^3*H20-432*B9*B29^4*H20-21600*K16*B29^2*H21+1512*K16*B29^3*H21+1296*K16*B29^4*H21+5184*G20*B29^2*P9-2016*B9*B29^2*H21-792*B9*B29^3*H21+432*B9*B29^4*H21-3024*K16*B29^2*P9-2592*K16*B29^3*P9+1584*B9*B29^2*P9-864*B9*B29^3*P9-5184*G20^2*B29*B32-21204*K16^2*B29*B32-52*B9^2*B29*B32+7776*B29^3*H20*H21-2592*B29^4*H20*H21-15552*B29^2*H20*P9+5184*B29^3*H20*P9+20736*B29^2*H21*P9-5184*B29^3*H21*P9-26784*K16^2*B29*B28-1248*B9^2*B29*B28-5184*B29*H20^2*B32-20736*B29*H20^2*B28-1800*B31*K16^2*B29^2+126*B31*K16^2*B29^3+108*B31*K16^2*B29^4+280*B31*B9^2*B29^2+110*B31*B9^2*B29^3-60*B31*B9^2*B29^4-20736*B7^2*B29*O15^2+41472*B29^2*H20*P9*B28-10368*B29^3*H20*P9*B28-41472*B29^2*H21*P9*B28+10368*B29^3*H21*P9*B28+10368*B29*H20^2*B32*B28+9*B31^2*K16^2*B29^2*B32^2+36*B31^2*K16^2*B29^3*B32^2+36*B31^2*K16^2*B29^4*B32^2+25*B31^2*B9^2*B29^2*B32^2+100*B31^2*B9^2*B29^3*B32^2+100*B31^2*B9^2*B29^4*B32^2+144*B31^2*K16^2*B29^2*B28^2-144*B31^2*K16^2*B29^3*B28^2+36*B31^2*K16^2*B29^4*B28^2+400*B31^2*B9^2*B29^2*B28^2-400*B31^2*B9^2*B29^3*B28^2+100*B31^2*B9^2*B29^4*B28^2+20736*B7^2*B29^2*P16^2*B8^2+5184*G20^2*B29^2*B32^2*B28^2+12996*K16^2*B29^2*B32^2*B28^2-8208*K16^2*B29^3*B32^2*B28^2+1296*K16^2*B29^4*B32^2*B28^2

V20.2 = 4*B9^2*B29^2*B32^2*B28^2-48*B9^2*B29^3*B32^2*B28^2+144*B9^2*B29^4*B32^2*B28^2+5184*B29^2*H20^2*B32^2*B28^2-10368*B29^3*H20^2*B32^2*B28^2+5184*B29^4*H20^2*B32^2*B28^2+5184*B29^4*H21^2*B32^2*B28^2-120*B31^2*K16*B9*B29^2+120*B31^2*K16*B9*B29^3-30*B31^2*K16*B9*B29^4-4104*G20*K16*B29^2*B32^2+1296*G20*K16*B29^3*B32^2-72*G20*B9*B29^2*B32^2+432*G20*B9*B29^3*B32^2+1206*B31*K16^2*B29^2*B32-234*B31*K16^2*B29^3*B32-324*B31*K16^2*B29^4*B32-490*B31*B9^2*B29^2*B32-50*B31*B9^2*B29^3*B32+180*B31*B9^2*B29^4*B32+114*K16*B9*B29^2*B32^2-720*K16*B9*B29^3*B32^2+216*K16*B9*B29^4*B32^2+2736*B31*K16^2*B29^2*B28+612*B31*K16^2*B29^3*B28-432*B31*K16^2*B29^4*B28-80*B31*B9^2*B29^2*B28-700*B31*B9^2*B29^3*B28+240*B31*B9^2*B29^4*B28+2592*G20*B29^2*H20*B32^2-2592*G20*B29^3*H20*B32^2+3456*K16*B9*B29^2*B28^2-3456*K16*B9*B29^3*B28^2+864*K16*B9*B29^4*B28^2-2592*G20*B29^3*H21*B32^2-4104*K16*B29^2*H20*B32^2+5400*K16*B29^3*H20*B32^2-1296*K16*B29^4*H20*B32^2-72*B9*B29^2*H20*B32^2+504*B9*B29^3*H20*B32^2-432*B9*B29^4*H20*B32^2+4104*K16*B29^3*H21*B32^2-1296*K16*B29^4*H21*B32^2+72*B9*B29^3*H21*B32^2-432*B9*B29^4*H21*B32^2-20736*K16*B29^2*H20*B28^2+20736*K16*B29^3*H20*B28^2-5184*K16*B29^4*H20*B28^2-6912*B9*B29^2*H20*B28^2+6912*B9*B29^3*H20*B28^2-1728*B9*B29^4*H20*B28^2+20736*K16*B29^2*H21*B28^2-20736*K16*B29^3*H21*B28^2+5184*K16*B29^4*H21*B28^2+6912*B9*B29^2*H21*B28^2-6912*B9*B29^3*H21*B28^2+1728*B9*B29^4*H21*B28^2-2592*B29^3*H20*H21*B32^2+2592*B29^4*H20*H21*B32^2-5184*G20^2*B29^2*B32*B28-18180*K16^2*B29^2*B32*B28-6696*K16^2*B29^3*B32*B28+2592*K16^2*B29^4*B32*B28-580*B9^2*B29^2*B32*B28-41472*B29^2*H20*H21*B28^2-312*B9^2*B29^3*B32*B28+41472*B29^3*H20*H21*B28^2+288*B9^2*B29^4*B32*B28-10368*B29^4*H20*H21*B28^2+5184*B29^2*H20^2*B32*B28-25920*B29^3*H20^2*B32*B28+10368*B29^4*H20^2*B32*B28+20736*B29^3*H21^2*B32*B28-10368*B29^4*H21^2*B32*B28-864*G20*B31*K16*B29+1440*G20*B31*B9*B29-3408*B31*K16*B9*B29-20736*B7*G20*B29*O15-864*B31*K16*B29*H20+1440*B31*B9*B29*H20+43200*B7*K16*B29*O15+4032*B7*B9*B29*O15-1728*B31*K16*B29*P9+2880*B31*B9*B29*P9+21600*G20*K16*B29*B32+2016*G20*B9*B29*B32-3336*K16*B9*B29*B32+41472*B7*G20*P16*B8-20736*B7*B29*H21*O15+10368*G20*K16*B29*B28+3456*G20*B9*B29*B28+6912*B7*K16*P16*B8+23040*B7*B9*P16*B8-41472*B7*B29*P9*O15-10368*G20*B29*H20*B32-12672*K16*B9*B29*B28+21600*K16*B29*H20*B32+2016*B9*B29*H20*B32-10368*G20*B29*P9*B32-20736*G20*B29*H20*B28+41472*B7*H20*P16*B8+20736*G20*B29*H21*B28+16416*K16*B29*P9*B32+288*B9*B29*P9*B32+63936*K16*B29*H20*B28+10944*B9*B29*H20*B28-53568*K16*B29*H21*B28-7488*B9*B29*H21*B28+82944*B7*P9*P16*B8+20736*K16*B29*P9*B28+6912*B9*B29*P9*B28-10368*B29*H20*P9*B32+20736*B29*H20*H21*B28-41472*B29*H20*P9*B28+41472*B29*H21*P9*B28-342*B31*K16^2*B29^2*B32^2+36*B31^2*K16^2*B29^2*B32-576*B31*K16^2*B29^3*B32^2+54*B31^2*K16^2*B29^3*B32+216*B31*K16^2*B29^4*B32^2-36*B31^2*K16^2*B29^4*B32+10*B31*B9^2*B29^2*B32^2+100*B31^2*B9^2*B29^2*B32-40*B31*B9^2*B29^3*B32^2+150*B31^2*B9^2*B29^3*B32-120*B31*B9^2*B29^4*B32^2-100*B31^2*B9^2*B29^4*B32+1728*B31*K16^2*B29^2*B28^2-144*B31^2*K16^2*B29^2*B28-1728*B31*K16^2*B29^3*B28^2+144*B31^2*K16^2*B29^3*B28+432*B31*K16^2*B29^4*B28^2-36*B31^2*K16^2*B29^4*B28-960*B31*B9^2*B29^2*B28^2-400*B31^2*B9^2*B29^2*B28+960*B31*B9^2*B29^3*B28^2+400*B31^2*B9^2*B29^3*B28-240*B31*B9^2*B29^4*B28^2-100*B31^2*B9^2*B29^4*B28-82944*B7^2*B29*P16^2*B8^2-5184*G20^2*B29^2*B32^2*B28-16416*K16^2*B29^2*B32*B28^2-12996*K16^2*B29^2*B32^2*B28+13392*K16^2*B29^3*B32*B28^2

V20.3 = 8208*K16^2*B29^3*B32^2*B28-2592*K16^2*B29^4*B32*B28^2-1296*K16^2*B29^4*B32^2*B28-96*B9^2*B29^2*B32*B28^2-4*B9^2*B29^2*B32^2*B28+624*B9^2*B29^3*B32*B28^2+48*B9^2*B29^3*B32^2*B28-288*B9^2*B29^4*B32*B28^2-144*B9^2*B29^4*B32^2*B28-20736*B29^2*H20^2*B32*B28^2-5184*B29^2*H20^2*B32^2*B28+31104*B29^3*H20^2*B32*B28^2+10368*B29^3*H20^2*B32^2*B28-10368*B29^4*H20^2*B32*B28^2-5184*B29^4*H20^2*B32^2*B28-20736*B29^3*H21^2*B32*B28^2+10368*B29^4*H21^2*B32*B28^2-5184*B29^4*H21^2*B32^2*B28+864*G20*B31*K16*B29^2-216*G20*B31*K16*B29^3-1440*G20*B31*B9*B29^2+360*G20*B31*B9*B29^3+2832*B31*K16*B9*B29^2-276*B31*K16*B9*B29^3-144*B31*K16*B9*B29^4+5184*B7*G20*B29^2*O15+648*B31*K16*B29^3*H20-216*B31*K16*B29^4*H20-1080*B31*B9*B29^3*H20+360*B31*B9*B29^4*H20+864*B31*K16*B29^2*H21-864*B31*K16*B29^3*H21+216*B31*K16*B29^4*H21-3024*B7*K16*B29^2*O15-1440*B31*B9*B29^2*H21-2592*B7*K16*B29^3*O15+1440*B31*B9*B29^3*H21-360*B31*B9*B29^4*H21+1584*B7*B9*B29^2*O15-864*B7*B9*B29^3*O15+1728*B31*K16*B29^2*P9-432*B31*K16*B29^3*P9-2880*B31*B9*B29^2*P9+720*B31*B9*B29^3*P9-10800*G20*K16*B29^2*B32-1008*G20*B9*B29^2*B32+1116*B31*K16^2*B29*B32-260*B31*B9^2*B29*B32-15552*B7*B29^2*H20*O15+5184*B7*B29^3*H20*O15+3396*K16*B9*B29^2*B32

V20 = V20.1 + V20.2 + V20.3
V20
```


```{r, include=FALSE}
W20.1 = -432*K16*B9*B29^4*B32+20736*B7*B29^2*H21*O15-5184*B7*B29^3*H21*O15-10368*G20*K16*B29^2*B28+2592*G20*K16*B29^3*B28-3456*G20*B9*B29^2*B28+864*G20*B9*B29^3*B28-4464*B31*K16^2*B29*B28+10368*B7*B29^2*P9*O15+1040*B31*B9^2*B29*B28+5184*G20*B29^2*H20*B32+9216*K16*B9*B29^2*B28+288*K16*B9*B29^3*B28-864*K16*B9*B29^4*B28+10368*G20*B29^2*H21*B32-5184*G20*B29^3*H21*B32-15984*K16*B29^2*H20*B32-2592*K16*B29^3*H20*B32+2592*K16*B29^4*H20*B32-2736*B9*B29^2*H20*B32-864*B9*B29^3*H20*B32+864*B9*B29^4*H20*B32-21600*K16*B29^2*H21*B32+10800*K16*B29^3*H21*B32+5184*G20*B29^2*P9*B32-2016*B9*B29^2*H21*B32+1008*B9*B29^3*H21*B32+20736*G20*B29^2*H20*B28-5184*G20*B29^3*H20*B28-20736*G20*B29^2*H21*B28+5184*G20*B29^3*H21*B28-13392*K16*B29^2*P9*B32+2592*K16*B29^3*P9*B32-1872*B9*B29^2*P9*B32+864*B9*B29^3*P9*B32-43200*K16*B29^2*H20*B28-4752*K16*B29^3*H20*B28+5184*K16*B29^4*H20*B28-4032*B9*B29^2*H20*B28-4176*B9*B29^3*H20*B28+1728*B9*B29^4*H20*B28+32832*K16*B29^2*H21*B28+7344*K16*B29^3*H21*B28-5184*K16*B29^4*H21*B28+576*B9*B29^2*H21*B28+5040*B9*B29^3*H21*B28-1728*B9*B29^4*H21*B28+82944*B7^2*O15*P16*B8+10368*B29^2*H20*H21*B32-5184*B29^3*H20*H21*B32-20736*K16*B29^2*P9*B28+5184*K16*B29^3*P9*B28-6912*B9*B29^2*P9*B28+1728*B9*B29^3*P9*B28+10368*G20^2*B29*B32*B28+15552*B29^2*H20*P9*B32-5184*B29^3*H20*P9*B32+10368*B29^2*H21*P9*B32-5184*B29^3*H21*P9*B32+42408*K16^2*B29*B32*B28+104*B9^2*B29*B32*B28+20736*B29^2*H20*H21*B28-36288*B29^3*H20*H21*B28+10368*B29^4*H20*H21*B28-16416*G20*K16*B29^2*B32^2*B28^2+5184*G20*K16*B29^3*B32^2*B28^2-288*G20*B9*B29^2*B32^2*B28^2+1728*G20*B9*B29^3*B32^2*B28^2-1872*B31*K16^2*B29^2*B32*B28^2+1368*B31*K16^2*B29^2*B32^2*B28-144*B31^2*K16^2*B29^2*B32*B28+3528*B31*K16^2*B29^3*B32*B28^2+2304*B31*K16^2*B29^3*B32^2*B28-216*B31^2*K16^2*B29^3*B32*B28-1296*B31*K16^2*B29^4*B32*B28^2-864*B31*K16^2*B29^4*B32^2*B28+144*B31^2*K16^2*B29^4*B32*B28-400*B31*B9^2*B29^2*B32*B28^2-40*B31*B9^2*B29^2*B32^2*B28-400*B31^2*B9^2*B29^2*B32*B28-1240*B31*B9^2*B29^3*B32*B28^2+160*B31*B9^2*B29^3*B32^2*B28-600*B31^2*B9^2*B29^3*B32*B28+720*B31*B9^2*B29^4*B32*B28^2+480*B31*B9^2*B29^4*B32^2*B28+400*B31^2*B9^2*B29^4*B32*B28+456*K16*B9*B29^2*B32^2*B28^2-2880*K16*B9*B29^3*B32^2*B28^2+864*K16*B9*B29^4*B32^2*B28^2+10368*G20*B29^2*H20*B32^2*B28^2-10368*G20*B29^3*H20*B32^2*B28^2-10368*G20*B29^3*H21*B32^2*B28^2-16416*K16*B29^2*H20*B32^2*B28^2+21600*K16*B29^3*H20*B32^2*B28^2-5184*K16*B29^4*H20*B32^2*B28^2-288*B9*B29^2*H20*B32^2*B28^2+2016*B9*B29^3*H20*B32^2*B28^2-1728*B9*B29^4*H20*B32^2*B28^2+16416*K16*B29^3*H21*B32^2*B28^2-5184*K16*B29^4*H21*B32^2*B28^2+288*B9*B29^3*H21*B32^2*B28^2-1728*B9*B29^4*H21*B32^2*B28^2-10368*B29^3*H20*H21*B32^2*B28^2+10368*B29^4*H20*H21*B32^2*B28^2+1728*B7*B31*K16*B29^2*O15-432*B7*B31*K16*B29^3*O15-2880*B7*B31*B9*B29^2*O15+720*B7*B31*B9*B29^3*O15-216*G20*B31*K16*B29^2*B32+216*G20*B31*K16*B29^3*B32+360*G20*B31*B9*B29^2*B32-360*G20*B31*B9*B29^3*B32-1716*B31*K16*B9*B29^2*B32+420*B31*K16*B9*B29^3*B32+432*B31*K16*B9*B29^4*B32-1728*G20*B31*K16*B29^2*B28+432*G20*B31*K16*B29^3*B28+2880*G20*B31*B9*B29^2*B28-720*G20*B31*B9*B29^3*B28-4512*B31*K16*B9*B29^2*B28-600*B31*K16*B9*B29^3*B28+576*B31*K16*B9*B29^4*B28+5184*B7*G20*B29^2*O15*B32-648*B31*K16*B29^2*H20*B32-864*B31*K16*B29^3*H20*B32+648*B31*K16*B29^4*H20*B32+1080*B31*B9*B29^2*H20*B32+1440*B31*B9*B29^3*H20*B32-1080*B31*B9*B29^4*H20*B32+432*B31*K16*B29^2*H21*B32+216*B31*K16*B29^3*H21*B32-216*B31*K16*B29^4*H21*B32+10368*B7*G20*B29^2*P16*B8-13392*B7*K16*B29^2*O15*B32-720*B31*B9*B29^2*H21*B32+2592*B7*K16*B29^3*O15*B32-360*B31*B9*B29^3*H21*B32+360*B31*B9*B29^4*H21*B32-1872*B7*B9*B29^2*O15*B32

W20.2 = 864*B7*B9*B29^3*O15*B32+43200*B7*K16*B29^2*P16*B8-10368*B7*K16*B29^3*P16*B8-1296*B31*K16*B29^2*P9*B32+864*B31*K16*B29^3*P9*B32+19584*B7*B9*B29^2*P16*B8-3456*B7*B9*B29^3*P16*B8+2160*B31*B9*B29^2*P9*B32-1440*B31*B9*B29^3*P9*B32+1728*B31*K16*B29^2*H20*B28-3024*B31*K16*B29^3*H20*B28+864*B31*K16*B29^4*H20*B28-2880*B31*B9*B29^2*H20*B28+5040*B31*B9*B29^3*H20*B28-1440*B31*B9*B29^4*H20*B28-3456*B31*K16*B29^2*H21*B28+3456*B31*K16*B29^3*H21*B28-864*B31*K16*B29^4*H21*B28-20736*B7*K16*B29^2*O15*B28+5760*B31*B9*B29^2*H21*B28+5184*B7*K16*B29^3*O15*B28-5760*B31*B9*B29^3*H21*B28+1440*B31*B9*B29^4*H21*B28-6912*B7*B9*B29^2*O15*B28+1728*B7*B9*B29^3*O15*B28-3456*B31*K16*B29^2*P9*B28+864*B31*K16*B29^3*P9*B28+15552*B7*B29^2*H20*O15*B32-5184*B7*B29^3*H20*O15*B32+5760*B31*B9*B29^2*P9*B28-1440*B31*B9*B29^3*P9*B28+10368*B7*B29^2*H21*O15*B32-5184*B7*B29^3*H21*O15*B32-31104*B7*B29^2*H20*P16*B8+10368*B7*B29^3*H20*P16*B8+16416*G20*K16*B29^2*B32*B28+2592*G20*K16*B29^3*B32*B28+41472*B7*B29^2*H21*P16*B8+288*G20*B9*B29^2*B32*B28-10368*B7*B29^3*H21*P16*B8+864*G20*B9*B29^3*B32*B28-2232*B31*K16^2*B29*B32*B28+520*B31*B9^2*B29*B32*B28+41472*B7*B29^2*H20*O15*B28-10368*B7*B29^3*H20*O15*B28-3912*K16*B9*B29^2*B32*B28-3168*K16*B9*B29^3*B32*B28+1728*K16*B9*B29^4*B32*B28-41472*B7*B29^2*H21*O15*B28+20736*B7*B29^2*P9*P16*B8+10368*B7*B29^3*H21*O15*B28-82944*B7^2*B29*O15*P16*B8-5184*G20*B29^3*H20*B32*B28-31104*G20*B29^2*H21*B32*B28+15552*G20*B29^3*H21*B32*B28+10368*K16*B29^2*H20*B32*B28+26352*K16*B29^3*H20*B32*B28-10368*K16*B29^4*H20*B32*B28+3456*B9*B29^2*H20*B32*B28+6192*B9*B29^3*H20*B32*B28-3456*B9*B29^4*H20*B32*B28+59616*K16*B29^2*H21*B32*B28-29808*K16*B29^3*H21*B32*B28-10368*G20*B29^2*P9*B32*B28+4320*B9*B29^2*H21*B32*B28-2160*B9*B29^3*H21*B32*B28+26784*K16*B29^2*P9*B32*B28-5184*K16*B29^3*P9*B32*B28+3744*B9*B29^2*P9*B32*B28-1728*B9*B29^3*P9*B32*B28-31104*B29^2*H20*H21*B32*B28+15552*B29^3*H20*H21*B32*B28-31104*B29^2*H20*P9*B32*B28+10368*B29^3*H20*P9*B32*B28-20736*B29^2*H21*P9*B32*B28+10368*B29^3*H21*P9*B32*B28-1368*B31*K16^2*B29^2*B32^2*B28^2+144*B31^2*K16^2*B29^2*B32*B28^2-36*B31^2*K16^2*B29^2*B32^2*B28-2304*B31*K16^2*B29^3*B32^2*B28^2+216*B31^2*K16^2*B29^3*B32*B28^2-144*B31^2*K16^2*B29^3*B32^2*B28+864*B31*K16^2*B29^4*B32^2*B28^2-144*B31^2*K16^2*B29^4*B32*B28^2-144*B31^2*K16^2*B29^4*B32^2*B28+40*B31*B9^2*B29^2*B32^2*B28^2+400*B31^2*B9^2*B29^2*B32*B28^2-100*B31^2*B9^2*B29^2*B32^2*B28-160*B31*B9^2*B29^3*B32^2*B28^2+600*B31^2*B9^2*B29^3*B32*B28^2-400*B31^2*B9^2*B29^3*B32^2*B28-480*B31*B9^2*B29^4*B32^2*B28^2-400*B31^2*B9^2*B29^4*B32*B28^2-400*B31^2*B9^2*B29^4*B32^2*B28+216*G20*B31*K16*B29^2*B32^2+432*G20*B31*K16*B29^3*B32^2-360*G20*B31*B9*B29^2*B32^2-720*G20*B31*B9*B29^3*B32^2+564*B31*K16*B9*B29^2*B32^2-120*B31^2*K16*B9*B29^2*B32+984*B31*K16*B9*B29^3*B32^2-180*B31^2*K16*B9*B29^3*B32-288*B31*K16*B9*B29^4*B32^2+120*B31^2*K16*B9*B29^4*B32-2304*B31*K16*B9*B29^2*B28^2+480*B31^2*K16*B9*B29^2*B28

W20.3 = 2304*B31*K16*B9*B29^3*B28^2-480*B31^2*K16*B9*B29^3*B28-576*B31*K16*B9*B29^4*B28^2+120*B31^2*K16*B9*B29^4*B28+216*B31*K16*B29^2*H20*B32^2+216*B31*K16*B29^3*H20*B32^2-432*B31*K16*B29^4*H20*B32^2-360*B31*B9*B29^2*H20*B32^2-360*B31*B9*B29^3*H20*B32^2+720*B31*B9*B29^4*H20*B32^2-216*B31*K16*B29^3*H21*B32^2-432*B31*K16*B29^4*H21*B32^2+360*B31*B9*B29^3*H21*B32^2+720*B31*B9*B29^4*H21*B32^2-3456*B31*K16*B29^2*H20*B28^2+3456*B31*K16*B29^3*H20*B28^2-864*B31*K16*B29^4*H20*B28^2+5760*B31*B9*B29^2*H20*B28^2-5760*B31*B9*B29^3*H20*B28^2+1440*B31*B9*B29^4*H20*B28^2+3456*B31*K16*B29^2*H21*B28^2-3456*B31*K16*B29^3*H21*B28^2+864*B31*K16*B29^4*H21*B28^2-5760*B31*B9*B29^2*H21*B28^2+5760*B31*B9*B29^3*H21*B28^2-1440*B31*B9*B29^4*H21*B28^2+10368*G20*K16*B29^2*B32*B28^2+16416*G20*K16*B29^2*B32^2*B28-5184*G20*K16*B29^3*B32*B28^2-5184*G20*K16*B29^3*B32^2*B28+3456*G20*B9*B29^2*B32*B28^2+288*G20*B9*B29^2*B32^2*B28-1728*G20*B9*B29^3*B32*B28^2-1728*G20*B9*B29^3*B32^2*B28-1476*B31*K16^2*B29^2*B32*B28-1296*B31*K16^2*B29^3*B32*B28+1296*B31*K16^2*B29^4*B32*B28+1180*B31*B9^2*B29^2*B32*B28+720*B31*B9^2*B29^3*B32*B28-720*B31*B9^2*B29^4*B32*B28-5760*K16*B9*B29^2*B32*B28^2-456*K16*B9*B29^2*B32^2*B28+6336*K16*B9*B29^3*B32*B28^2+2880*K16*B9*B29^3*B32^2*B28-1728*K16*B9*B29^4*B32*B28^2-864*K16*B9*B29^4*B32^2*B28+20736*B7^2*B29^2*O15*P16*B8-20736*G20*B29^2*H20*B32*B28^2-10368*G20*B29^2*H20*B32^2*B28+10368*G20*B29^3*H20*B32*B28^2+10368*G20*B29^3*H20*B32^2*B28+20736*G20*B29^2*H21*B32*B28^2-10368*G20*B29^3*H21*B32*B28^2+10368*G20*B29^3*H21*B32^2*B28+43200*K16*B29^2*H20*B32*B28^2+16416*K16*B29^2*H20*B32^2*B28-42336*K16*B29^3*H20*B32*B28^2

W20 = W20.1 + W20.2 + W20.3
W20
```

```{r, include=FALSE}
X20.1 = -21600*K16*B29^3*H20*B32^2*B28+10368*K16*B29^4*H20*B32*B28^2+5184*K16*B29^4*H20*B32^2*B28+4032*B9*B29^2*H20*B32*B28^2+288*B9*B29^2*H20*B32^2*B28-8928*B9*B29^3*H20*B32*B28^2-2016*B9*B29^3*H20*B32^2*B28+3456*B9*B29^4*H20*B32*B28^2+1728*B9*B29^4*H20*B32^2*B28-32832*K16*B29^2*H21*B32*B28^2+16416*K16*B29^3*H21*B32*B28^2-16416*K16*B29^3*H21*B32^2*B28+5184*K16*B29^4*H21*B32^2*B28-576*B9*B29^2*H21*B32*B28^2+288*B9*B29^3*H21*B32*B28^2-288*B9*B29^3*H21*B32^2*B28+1728*B9*B29^4*H21*B32^2*B28+20736*B29^2*H20*H21*B32*B28^2-10368*B29^3*H20*H21*B32*B28^2+10368*B29^3*H20*H21*B32^2*B28-10368*B29^4*H20*H21*B32^2*B28+36*B31^2*K16^2*B29^2*B32^2*B28^2+144*B31^2*K16^2*B29^3*B32^2*B28^2+144*B31^2*K16^2*B29^4*B32^2*B28^2+100*B31^2*B9^2*B29^2*B32^2*B28^2+400*B31^2*B9^2*B29^3*B32^2*B28^2+400*B31^2*B9^2*B29^4*B32^2*B28^2-1728*B7*B31*K16*B29*O15+2880*B7*B31*B9*B29*O15-432*G20*B31*K16*B29*B32+720*G20*B31*B9*B29*B32-1704*B31*K16*B9*B29*B32+1728*G20*B31*K16*B29*B28-2880*G20*B31*B9*B29*B28+6816*B31*K16*B9*B29*B28-10368*B7*G20*B29*O15*B32-432*B31*K16*B29*H20*B32+720*B31*B9*B29*H20*B32-41472*B7*G20*B29*P16*B8+16416*B7*K16*B29*O15*B32+288*B7*B9*B29*O15*B32-48384*B7*K16*B29*P16*B8-864*B31*K16*B29*P9*B32-36864*B7*B9*B29*P16*B8+1440*B31*B9*B29*P9*B32+1728*B31*K16*B29*H20*B28-2880*B31*B9*B29*H20*B28+20736*B7*K16*B29*O15*B28+6912*B7*B9*B29*O15*B28+3456*B31*K16*B29*P9*B28-10368*B7*B29*H20*O15*B32-5760*B31*B9*B29*P9*B28-43200*G20*K16*B29*B32*B28-41472*B7*B29*H21*P16*B8-4032*G20*B9*B29*B32*B28-41472*B7*B29*H20*O15*B28+6672*K16*B9*B29*B32*B28+41472*B7*B29*H21*O15*B28-82944*B7*B29*P9*P16*B8+20736*G20*B29*H20*B32*B28-43200*K16*B29*H20*B32*B28-4032*B9*B29*H20*B32*B28+20736*G20*B29*P9*B32*B28-30*B31^2*K16*B9*B29^2*B32^2-120*B31^2*K16*B9*B29^3*B32^2-120*B31^2*K16*B9*B29^4*B32^2-32832*K16*B29*P9*B32*B28-576*B9*B29*P9*B32*B28-480*B31^2*K16*B9*B29^2*B28^2+480*B31^2*K16*B9*B29^3*B28^2-120*B31^2*K16*B9*B29^4*B28^2+20736*B29*H20*P9*B32*B28-864*B7*B31*K16*B29*O15*B32+1440*B7*B31*B9*B29*O15*B32+6912*B7*B31*K16*B29*P16*B8+9216*B7*B31*B9*B29*P16*B8+3456*B7*B31*K16*B29*O15*B28-5760*B7*B31*B9*B29*O15*B28+864*G20*B31*K16*B29*B32*B28-1440*G20*B31*B9*B29*B32*B28+3408*B31*K16*B9*B29*B32*B28-20736*B7*G20*B29*P16*B32*B8+38016*B7*K16*B29*P16*B32*B8+20736*B7*G20*B29*O15*B32*B28+2304*B7*B9*B29*P16*B32*B8+864*B31*K16*B29*H20*B32*B28-1440*B31*B9*B29*H20*B32*B28-32832*B7*K16*B29*O15*B32*B28-576*B7*B9*B29*O15*B32*B28+82944*B7*K16*B29*P16*B8*B28+1728*B31*K16*B29*P9*B32*B28+27648*B7*B9*B29*P16*B8*B28-2880*B31*B9*B29*P9*B32*B28-20736*B7*B29*H20*P16*B32*B8+20736*B7*B29*H20*O15*B32*B28-82944*B7*B29*H20*P16*B8*B28+82944*B7*B29*H21*P16*B8*B28+864*G20*B31*K16*B29^2*B32^2*B28^2+1728*G20*B31*K16*B29^3*B32^2*B28^2-1440*G20*B31*B9*B29^2*B32^2*B28^2-2880*G20*B31*B9*B29^3*B32^2*B28^2+2256*B31*K16*B9*B29^2*B32^2*B28^2-480*B31^2*K16*B9*B29^2*B32*B28^2+120*B31^2*K16*B9*B29^2*B32^2*B28+3936*B31*K16*B9*B29^3*B32^2*B28^2-720*B31^2*K16*B9*B29^3*B32*B28^2+480*B31^2*K16*B9*B29^3*B32^2*B28-1152*B31*K16*B9*B29^4*B32^2*B28^2+480*B31^2*K16*B9*B29^4*B32*B28^2+480*B31^2*K16*B9*B29^4*B32^2*B28+864*B31*K16*B29^2*H20*B32^2*B28^2+864*B31*K16*B29^3*H20*B32^2*B28^2-1728*B31*K16*B29^4*H20*B32^2*B28^2-1440*B31*B9*B29^2*H20*B32^2*B28^2-1440*B31*B9*B29^3*H20*B32^2*B28^2+2880*B31*B9*B29^4*H20*B32^2*B28^2-864*B31*K16*B29^3*H21*B32^2*B28^2-1728*B31*K16*B29^4*H21*B32^2*B28^2+1440*B31*B9*B29^3*H21*B32^2*B28^2+2880*B31*B9*B29^4*H21*B32^2*B28^2-1296*B7*B31*K16*B29^2*O15*B32+864*B7*B31*K16*B29^3*O15*B32+2160*B7*B31*B9*B29^2*O15*B32-1440*B7*B31*B9*B29^3*O15*B32-6912*B7*B31*K16*B29^2*P16*B8

X20.2 = 1728*B7*B31*K16*B29^3*P16*B8-9216*B7*B31*B9*B29^2*P16*B8+2304*B7*B31*B9*B29^3*P16*B8-3456*B7*B31*K16*B29^2*O15*B28+864*B7*B31*K16*B29^3*O15*B28+5760*B7*B31*B9*B29^2*O15*B28-1440*B7*B31*B9*B29^3*O15*B28-432*G20*B31*K16*B29^2*B32*B28+720*G20*B31*B9*B29^2*B32*B28+1752*B31*K16*B9*B29^2*B32*B28+1728*B31*K16*B9*B29^3*B32*B28-1728*B31*K16*B9*B29^4*B32*B28+10368*B7*G20*B29^2*P16*B32*B8-39744*B7*K16*B29^2*P16*B32*B8+10368*B7*K16*B29^3*P16*B32*B8-10368*B7*G20*B29^2*O15*B32*B28-8064*B7*B9*B29^2*P16*B32*B8+3456*B7*B9*B29^3*P16*B32*B8+1296*B31*K16*B29^2*H20*B32*B28+4320*B31*K16*B29^3*H20*B32*B28-2592*B31*K16*B29^4*H20*B32*B28-2160*B31*B9*B29^2*H20*B32*B28-7200*B31*B9*B29^3*H20*B32*B28+4320*B31*B9*B29^4*H20*B32*B28-1728*B31*K16*B29^2*H21*B32*B28-864*B31*K16*B29^3*H21*B32*B28+864*B31*K16*B29^4*H21*B32*B28+26784*B7*K16*B29^2*O15*B32*B28+2880*B31*B9*B29^2*H21*B32*B28-5184*B7*K16*B29^3*O15*B32*B28+1440*B31*B9*B29^3*H21*B32*B28-1440*B31*B9*B29^4*H21*B32*B28+3744*B7*B9*B29^2*O15*B32*B28-1728*B7*B9*B29^3*O15*B32*B28-82944*B7*K16*B29^2*P16*B8*B28+20736*B7*K16*B29^3*P16*B8*B28+2592*B31*K16*B29^2*P9*B32*B28-1728*B31*K16*B29^3*P9*B32*B28-27648*B7*B9*B29^2*P16*B8*B28+6912*B7*B9*B29^3*P16*B8*B28-4320*B31*B9*B29^2*P9*B32*B28+2880*B31*B9*B29^3*P9*B32*B28+31104*B7*B29^2*H20*P16*B32*B8-10368*B7*B29^3*H20*P16*B32*B8+20736*B7*B29^2*H21*P16*B32*B8-10368*B7*B29^3*H21*P16*B32*B8-31104*B7*B29^2*H20*O15*B32*B28+10368*B7*B29^3*H20*O15*B32*B28-20736*B7*B29^2*H21*O15*B32*B28+10368*B7*B29^3*H21*O15*B32*B28+82944*B7*B29^2*H20*P16*B8*B28-20736*B7*B29^3*H20*P16*B8*B28-82944*B7*B29^2*H21*P16*B8*B28+20736*B7*B29^3*H21*P16*B8*B28-120*B31^2*K16*B9*B29^2*B32^2*B28^2-480*B31^2*K16*B9*B29^3*B32^2*B28^2-480*B31^2*K16*B9*B29^4*B32^2*B28^2+1728*G20*B31*K16*B29^2*B32*B28^2-864*G20*B31*K16*B29^2*B32^2*B28-864*G20*B31*K16*B29^3*B32*B28^2-1728*G20*B31*K16*B29^3*B32^2*B28-2880*G20*B31*B9*B29^2*B32*B28^2+1440*G20*B31*B9*B29^2*B32^2*B28+1440*G20*B31*B9*B29^3*B32*B28^2+2880*G20*B31*B9*B29^3*B32^2*B28+3360*B31*K16*B9*B29^2*B32*B28^2-2256*B31*K16*B9*B29^2*B32^2*B28+480*B31^2*K16*B9*B29^2*B32*B28-5136*B31*K16*B9*B29^3*B32*B28^2-3936*B31*K16*B9*B29^3*B32^2*B28

X20.3 = 720*B31^2*K16*B9*B29^3*B32*B28+1728*B31*K16*B9*B29^4*B32*B28^2+1152*B31*K16*B9*B29^4*B32^2*B28-480*B31^2*K16*B9*B29^4*B32*B28-864*B31*K16*B29^2*H20*B32^2*B28-5184*B31*K16*B29^3*H20*B32*B28^2-864*B31*K16*B29^3*H20*B32^2*B28+2592*B31*K16*B29^4*H20*B32*B28^2+1728*B31*K16*B29^4*H20*B32^2*B28+1440*B31*B9*B29^2*H20*B32^2*B28+8640*B31*B9*B29^3*H20*B32*B28^2+1440*B31*B9*B29^3*H20*B32^2*B28-4320*B31*B9*B29^4*H20*B32*B28^2-2880*B31*B9*B29^4*H20*B32^2*B28+1728*B31*K16*B29^2*H21*B32*B28^2+864*B31*K16*B29^3*H21*B32*B28^2+864*B31*K16*B29^3*H21*B32^2*B28-864*B31*K16*B29^4*H21*B32*B28^2+1728*B31*K16*B29^4*H21*B32^2*B28-2880*B31*B9*B29^2*H21*B32*B28^2-1440*B31*B9*B29^3*H21*B32*B28^2-1440*B31*B9*B29^3*H21*B32^2*B28+1440*B31*B9*B29^4*H21*B32*B28^2-2880*B31*B9*B29^4*H21*B32^2*B28+3456*B7*B31*K16*B29*P16*B32*B8+4608*B7*B31*B9*B29*P16*B32*B8+1728*B7*B31*K16*B29*O15*B32*B28-2880*B7*B31*B9*B29*O15*B32*B28-13824*B7*B31*K16*B29*P16*B8*B28-18432*B7*B31*B9*B29*P16*B8*B28+41472*B7*G20*B29*P16*B32*B8*B28-76032*B7*K16*B29*P16*B32*B8*B28-4608*B7*B9*B29*P16*B32*B8*B28+41472*B7*B29*H20*P16*B32*B8*B28+5184*B7*B31*K16*B29^2*P16*B32*B8-3456*B7*B31*K16*B29^3*P16*B32*B8+6912*B7*B31*B9*B29^2*P16*B32*B8-4608*B7*B31*B9*B29^3*P16*B32*B8+2592*B7*B31*K16*B29^2*O15*B32*B28-1728*B7*B31*K16*B29^3*O15*B32*B28-4320*B7*B31*B9*B29^2*O15*B32*B28+2880*B7*B31*B9*B29^3*O15*B32*B28+13824*B7*B31*K16*B29^2*P16*B8*B28-3456*B7*B31*K16*B29^3*P16*B8*B28+18432*B7*B31*B9*B29^2*P16*B8*B28-4608*B7*B31*B9*B29^3*P16*B8*B28-20736*B7*G20*B29^2*P16*B32*B8*B28+79488*B7*K16*B29^2*P16*B32*B8*B28-20736*B7*K16*B29^3*P16*B32*B8*B28+16128*B7*B9*B29^2*P16*B32*B8*B28-6912*B7*B9*B29^3*P16*B32*B8*B28-62208*B7*B29^2*H20*P16*B32*B8*B28+20736*B7*B29^3*H20*P16*B32*B8*B28-41472*B7*B29^2*H21*P16*B32*B8*B28+20736*B7*B29^3*H21*P16*B32*B8*B28-10368*B7*B31*K16*B29^2*P16*B32*B8*B28+6912*B7*B31*K16*B29^3*P16*B32*B8*B28-13824*B7*B31*B9*B29^2*P16*B32*B8*B28+9216*B7*B31*B9*B29^3*P16*B32*B8*B28-6912*B7*B31*K16*B29*P16*B32*B8*B28-9216*B7*B31*B9*B29*P16*B32*B8*B28

X20 = X20.1 + X20.2 +X20.3
X20

```

```{r, include=FALSE}
Y20 = (V20+W20+X20)^(1/2)
Y20
```

```{r, include=FALSE}
#V21 Pre-Calculations

P15 = (72*G20-186*K16-26*B9+72*H20+144*P9+18*K16*B29^2+6*B9*B29^2-36*B29^2*H20+36*B29^2*H21+Y20-36*G20*B29+57*K16*B29+B9*B29+144*B7*O15+36*B29*H20-72*B29*H21-72*B29*P9-6*B31*K16*B29+10*B31*B9*B29-72*B7*B29*O15-36*G20*B29*B32+57*K16*B29*B32+B9*B29*B32-288*B7*P16*B8+72*K16*B29*B28+24*B9*B29*B28-36*B29*H20*B32-144*B29*H20*B28+144*B29*H21*B28+3*B31*K16*B29^2-5*B31*B9*B29^2-18*K16*B29^2*B32-6*B9*B29^2*B32-36*K16*B29^2*B28-12*B9*B29^2*B28+36*B29^2*H20*B32+36*B29^2*H21*B32+72*B29^2*H20*B28-72*B29^2*H21*B28-72*B29^2*H20*B32*B28-72*B29^2*H21*B32*B28-3*B31*K16*B29*B32+5*B31*B9*B29*B32+12*B31*K16*B29*B28-20*B31*B9*B29*B28+144*B7*B29*P16*B8+72*G20*B29*B32*B28-114*K16*B29*B32*B28-2*B9*B29*B32*B28+72*B29*H20*B32*B28-6*B31*K16*B29^2*B32+10*B31*B9*B29^2*B32-6*B31*K16*B29^2*B28+10*B31*B9*B29^2*B28+36*K16*B29^2*B32*B28+12*B9*B29^2*B32*B28+12*B31*K16*B29^2*B32*B28-20*B31*B9*B29^2*B32*B28+6*B31*K16*B29*B32*B28-10*B31*B9*B29*B32*B28)/(144*(2*B7-B7*B29))

K7 = (K16+1/3*B9)/(2+4*B8*P16/P15)
K8 = K8 = K7*2*B8*P16/P15
K10 = 2*K7+3/2*K8-B9/3
K12 = K7+K8
K11 = 5/3*K12

K9 = K10-K11

O24 = B32/(1-0.5*B29)*((1-B29)/2*(H20-H21+1/2*K8-K7-2*K8-1/2*B31*K9)+(0.5*G20-0.25*(1-B31)*(1/3*K7*(1-B8*P16/P15)-1/3*B9)-K7*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21)))


```


```{r, include=FALSE}
V21 = (0.5*G20-0.25*(1-B31)*(1/3*K7*(1-B8*P16/P15)-1/3*B9)-K7*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21+O24))+(1-B29)/2*(H20-H21-O24+1/2*K8-K7-2*K8-1/2*B31*K9)+(1-B28)*B29*(H20-H21-O24+1/2*K8-K7-2*K8-1/2*B31*K9)

V21
```

```{r, include=FALSE}
W21 = -P15+O15+((0.5*G20-0.25*(1-B31)*(1/3*K7*(1-B8*P16/P15)-1/3*B9)-K7*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21+B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-K9*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9-K7*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))))+(1-B29)/2*(H20-H21-B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-K9*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9-K7*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))+1/2*K8-K7-2*K8-1/2*B31*K9)+(1-B28)*B29*(H20-H21-B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-K9*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9-K7*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))+1/2*K8-K7-2*K8-1/2*B31*K9)+P9-(K16+1/3*B9)/(2+4*B8*P16/P15)+(K16+1/3*B9)/(2+4*B8*P16/P15)*B8*P16/P15)/B7

W21
```

```{r, include=FALSE}
X21 = -P15+O15+((0.5*G20-0.25*(1-B31)*(1/3* (K16+1/3*B9)/(2+4*B8*P16/P15)*(1-B8*P16/P15)-1/3*B9)- (K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21+B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-K9*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9-(K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))))+(1-B29)/2*(H20-H21-B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-K9*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9- (K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))+1/2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15- (K16+1/3*B9)/(2+4*B8*P16/P15)-2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/2*B31*K9)+(1-B28)*B29*(H20-H21-B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-K9*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9-(K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))+1/2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15- (K16+1/3*B9)/(2+4*B8*P16/P15)-2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/2*B31*K9)+P9-(K16+1/3*B9)/(2+4*B8*P16/P15)+(K16+1/3*B9)/(2+4*B8*P16/P15)*B8*P16/P15)/B7

X21
```

```{r, include=FALSE}
Y21 = -P15+O15+((0.5*G20-0.25*(1-B31)*(1/3* (K16+1/3*B9)/(2+4*B8*P16/P15)*(1-B8*P16/P15)-1/3*B9)- (K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21+B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-(1/3*(K16+1/3*B9)/(2+4*B8*P16/P15)-1/6*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/3*B9)*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9- (K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))))+(1-B29)/2*(H20-H21-B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-(1/3*(K16+1/3*B9)/(2+4*B8*P16/P15)-1/6*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/3*B9)*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9-(K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))+1/2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-(K16+1/3*B9)/(2+4*B8*P16/P15)-2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/2*B31*(1/3*(K16+1/3*B9)/(2+4*B8*P16/P15)-1/6*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/3*B9))+(1-B28)*B29*(H20-H21-B32/(1-0.5*B29)*((1-B29)/2*H20-B29/2*H21+1/2*G20-(1/3*(K16+1/3*B9)/(2+4*B8*P16/P15)-1/6*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/3*B9)*(1/4-1/4*B31-1/2*B29*B31)+1/6*B9- (K16+1/3*B9)/(2+4*B8*P16/P15)*(1+2*B8*P16/P15*(1+3/4*(1-B29))+(1-B29)/2))+1/2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15- (K16+1/3*B9)/(2+4*B8*P16/P15)-2*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/2*B31*(1/3*(K16+1/3*B9)/(2+4*B8*P16/P15)-1/6*(K16+1/3*B9)/(2+4*B8*P16/P15)*2*B8*P16/P15-1/3*B9))+P9-(K16+1/3*B9)/(2+4*B8*P16/P15)+(K16+1/3*B9)/(2+4*B8*P16/P15)*B8*P16/P15)/B7

Y21
```

```{r, include=FALSE}
V22 = (72*G20-186*K16-26*B9+72*H20+144*P9+18*K16*B29^2+6*B9*B29^2-36*B29^2*H20+36*B29^2*H21+Y20-36*G20*B29+57*K16*B29+B9*B29+144*B7*O15+36*B29*H20-72*B29*H21-72*B29*P9-6*B31*K16*B29+10*B31*B9*B29-72*B7*B29*O15-36*G20*B29*B32+57*K16*B29*B32+B9*B29*B32-288*B7*P16*B8+72*K16*B29*B28+24*B9*B29*B28-36*B29*H20*B32-144*B29*H20*B28+144*B29*H21*B28+3*B31*K16*B29^2-5*B31*B9*B29^2-18*K16*B29^2*B32-6*B9*B29^2*B32-36*K16*B29^2*B28-12*B9*B29^2*B28+36*B29^2*H20*B32+36*B29^2*H21*B32+72*B29^2*H20*B28-72*B29^2*H21*B28-72*B29^2*H20*B32*B28-72*B29^2*H21*B32*B28-3*B31*K16*B29*B32+5*B31*B9*B29*B32+12*B31*K16*B29*B28-20*B31*B9*B29*B28+144*B7*B29*P16*B8+72*G20*B29*B32*B28-114*K16*B29*B32*B28-2*B9*B29*B32*B28+72*B29*H20*B32*B28-6*B31*K16*B29^2*B32+10*B31*B9*B29^2*B32-6*B31*K16*B29^2*B28+10*B31*B9*B29^2*B28+36*K16*B29^2*B32*B28+12*B9*B29^2*B32*B28+12*B31*K16*B29^2*B32*B28-20*B31*B9*B29^2*B32*B28+6*B31*K16*B29*B32*B28-10*B31*B9*B29*B32*B28)/(144*(2*B7-B7*B29))

V22
```


```{r, include=FALSE}
#Overall Rates Pre-Calculations

O24 = B32/(1-0.5*B29)*((1-B29)/2*(H20-H21+1/2*K8-K7-2*K8-1/2*B31*K9)+(0.5*G20-0.25*(1-B31)*(1/3*K7*(1-B8*P16/P15)-1/3*B9)-K7*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21)))
K27 = B29*(H20-H21-O24+1/2*K8-K7-2*K8-1/2*B31*K9)
P11 = (1-B29)/2*(H20-H21-O24+1/2*K8-K7-2*K8-1/2*B31*K9)
O11 = (0.5*G20-0.25*(1-B31)*(1/3*K7*(1-B8*P16/P15)-1/3*B9)-K7*(1+2*B8*P16/P15)+1/6*B9+0.5*(H21+O24))


```


```{r, include=FALSE}
#Overall Rates
OverallRates = {}


OverallRates["A"] = K5 = K7-0.5*K8-B9
OverallRates["GA"] = K6 = K5+B9
OverallRates["Vc"] = K7
OverallRates["Vo"] = K8
OverallRates["Carb Synthesis CS TOT"] = K9
OverallRates["PGA Reduction PR TOT"] = K10
OverallRates["DHAP Entering RPP"] = K11
OverallRates["RuP Phosphorylation"] = K12
OverallRates["GDC TOT"] = K13 = K8
OverallRates["NADPH Demand Tot"] = K14 = 1/2*K8+K10
OverallRates["ATP Demand Tot"] = K15 = K10+K7+2*K8+0.5*K9+K27+2*P11+2*O11
OverallRates["JNADPH"] = K16
OverallRates["ATP"] = K17 = G20+H20


OverallRatestab <- matrix(data = OverallRates)
rownames(OverallRatestab) <- c(names(OverallRates))
colnames(OverallRatestab) <- c("Value")
print("Overall Rates")
OverallRatestab
```

```{r, include=FALSE}
#CCM
CCM = {}

CCM["VP"] = K26 = O11+K27*(1-B28)+P11
CCM["PEPCK"] = K27
CCM["PH"] = K28 = K27*B28

CCMtab <- matrix(data = CCM)
rownames(CCMtab) <- c(names(CCM))
colnames(CCMtab) <- c("Value")
print("CCM")
CCMtab
```

```{r, include=FALSE}
#BS/M Partitioning Pre-Calculations
P7 = K8
P10 = K9*B31
P12 = (H21+O24-0.5*P7)
O6 = 0
O7 = 0
O14 = O6+O7
P6 = K7
P14 = P6+P7
```

```{r, include=FALSE}
MPartitioning = {}

MPartitioning["Vc"] = O6
MPartitioning["Vo"] = O7
MPartitioning["GDC"] = O8 = 0
MPartitioning["RLIGHT"] = O9 = B9-P9
MPartitioning["Carb Synthesis CS"] = O10 = K9-P10
MPartitioning["PPDK"] = O11
MPartitioning["PGA Reduction PR"] = O12 = K10-P12
MPartitioning["DHAP Entering RPP"] = O13 =  5/3*O14
MPartitioning["RuP Phosphorylation"] = O14
MPartitioning["C"] = O15
MPartitioning["O"] = O16 = B6

MPartitioningtab <- matrix(data = MPartitioning)
rownames(MPartitioningtab) <- c(names(MPartitioning))
colnames(MPartitioningtab) <- c("Value")
print("MPartitioning")
MPartitioningtab
```

```{r, include=FALSE}
BSPartitioning = {}

BSPartitioning["Vc"] = P6
BSPartitioning["Vo"] = P7
BSPartitioning["GDC"] = P8 = K13
BSPartitioning["RLIGHT"] = P9
BSPartitioning["Carb Synthesis CS"] = P10
BSPartitioning["PPDK"] = P11
BSPartitioning["PGA Reduction PR"] = P12
BSPartitioning["DHAP Entering RPP"] = P13 =  5/3*P14
BSPartitioning["RuP Phosphorylation"] = P14 
BSPartitioning["C"] = P15
BSPartitioning["O"] = P16

BSPartitioningtab <- matrix(data = BSPartitioning)
rownames(BSPartitioningtab) <- c(names(BSPartitioning))
colnames(BSPartitioningtab) <- c("Value")
print("BSPartitioning")
BSPartitioningtab

```

```{r, include=FALSE}
#MReducing Power Balance

MReducingPowerBalance = {}

MReducingPowerBalance["NADPH potent. avail."] = O22 = G21
MReducingPowerBalance["NADPH demand (excl. CCM"] = O23 = O12+0.5*O7-0.5*(O8-O7)
MReducingPowerBalance["MDH"] = O24
MReducingPowerBalance["Transamination T"] = O25 =  K26-O24
MReducingPowerBalance["ME"] = O26 = 0
MReducingPowerBalance["NADPH demand"] = O27 = O24+O23
MReducingPowerBalance["ATP demand"] = O28 = 2*O11++O6+2*O7+O10/2+O12+0.5*(O8-O7)

MReducingPowerBalancetab <- matrix(data = MReducingPowerBalance)
rownames(MReducingPowerBalancetab) <- c(names(MReducingPowerBalance))
colnames(MReducingPowerBalancetab) <- c("Value")
print("MReducingPowerBalance")
MReducingPowerBalancetab

```

```{r, include=FALSE}
#BSReducing Power Balance

BSReducingPowerBalance = {}

BSReducingPowerBalance["NADPH potent. avail."] = P22 = K26-K27
BSReducingPowerBalance["NADPH demand (excl. CCM"] = P23 = P12-0.5*(P8-P7)+0.5*P7
BSReducingPowerBalance["MDH"] = P24 = O25-K27
BSReducingPowerBalance["Transamination T"] = P25 = O25
BSReducingPowerBalance["ME"] = P26 = O24+P24
BSReducingPowerBalance["NADPH demand"] = P27 = P23-P26+P24
BSReducingPowerBalance["ATP demand"] = P28 = P12+P6+2*P7+2*P11+K27+0.5*P10+0.5*(P8-P7)

BSReducingPowerBalancetab <- matrix(data = BSReducingPowerBalance)
rownames(BSReducingPowerBalancetab) <- c(names(BSReducingPowerBalance))
colnames(BSReducingPowerBalancetab) <- c("Value")
print("BSReducingPowerBalance")
BSReducingPowerBalancetab

```

```{r, include=FALSE}
#Ratios Pre-Calculations
T19 = (K26+P9+1/2*P8-P6)
```

```{r, include=FALSE}
#Ratios

Ratios = {}


Ratios["ATP TOT / GA"] = T5 = K15/K6

if (typeof(T19/K26)=="double"){
  Ratios["Leakiness φ"] = T6 = T19/K26
  } else
    Ratios["Leakiness φ"] = T6 = 0

Ratios["ATP TOT / NADPH TOT"] = T7 = K15/K14
Ratios["NADPH BS / NADPH TOT"] = T8 = P23/K14

if (typeof(P23/O23)=="double"){
  Ratios["NADPH BS / NADPH M"] = T9 = P23/O23
  } else
    Ratios["NADPH BS / NADPH M"] = T9 = 0

if (typeof(P28/O28)=="double"){
    Ratios["ATP BS / ATP M"] = T10 = P28/O28
  } else
    Ratios["ATP BS / ATP M"] = T10 = 0

Ratios["ATP BS / ATP TOT"] = T11 = P28/K15

if (typeof(O28/O27)=="double"){
    Ratios["Photo-prod. ATP M / NADPH M"] = T12 = O28/O27
  } else
    Ratios["Photo-prod. ATP M / NADPH M"] = T12 = 0

if (typeof((K27+P24)/O24)=="double"){
    Ratios["ASP/MAL decarboxilation"] = T13 = (K27+P24)/O24
  } else
    Ratios["ASP/MAL decarboxilation"] = T13 = 0

if (typeof(O25/K26)=="double"){
    Ratios["T/VP"] = T14 = O25/K26
  } else
    Ratios["T/VP"] = T14 = 0


Ratios["(ATP TOT + NADPH TOT) / GA"] = T15 = (K15+K14)/K6

Ratiostab <- matrix(data = Ratios)
rownames(Ratiostab) <- c(names(Ratios))
colnames(Ratiostab) <- c("Value")
print("Ratios")
Ratiostab

```

```{r, include=FALSE}
#Fluxes Pre-Calculations
X30 = O7-O8
X31 = 1/2*X30
```

```{r, include=FALSE}
#Fluxes

Fluxes = {}

Fluxes["CO2 BS→M Leak rate L"] = T19
Fluxes["DHAP M→BS"] = T20 = O12-O10-O13
Fluxes["PGA BS→M"] = T21 = 2*P6+1.5*P7-P12-1/3*P9
Fluxes["MAL M→BS"] = T22 = O24
Fluxes["PEP BS→M"] = T23 = K27*(1-B28)+P11
Fluxes["ASP M→BS"] = T24 = O25
Fluxes["Pi M→BS"] = T25 = T23+T21-T20
Fluxes["ALA BS→M"] = T26 = T24+X31
Fluxes["PYR BS→M"] = T27 = P26-O25-X31-P11+B28*K27
Fluxes["Total fluxes"] = T28 =abs(T19)+abs(T20)+abs(T21)+abs(T22)+abs(T23)+abs(T24)+abs(X30)+abs(X31)+abs(T26)+abs(T27)+abs(T25)

Fluxestab <- matrix(data = Fluxes)
rownames(Fluxestab) <- c(names(Fluxes))
colnames(Fluxestab) <- c("Value")
print("Fluxes")
Fluxestab

```

```{r}
Mlightrxnstab
BSlightrxnstab
OverallRatestab
CCMtab
MPartitioningtab
BSPartitioningtab
MReducingPowerBalancetab
BSReducingPowerBalancetab
Ratiostab
Fluxestab





```